"""Digital Agency Agent şablon tanımı.

Müşteri alım, kampanya yönetimi, rapor oluşturma,
içerik takvimi, bütçe takibi, rakip analizi,
lead puanlama, fatura oluşturma, proje takibi,
müşteri iletişim becerileri ve iş akışları.
"""

DIGITAL_AGENCY_TEMPLATE = {
    "name": "Digital Agency Agent",
    "industry": "digital_agency",
    "version": "1.0.0",
    "description": "Dijital ajans operasyonları için tam kapsamlı AI agent şablonu. "
                   "Kampanya yönetimi, müşteri iletişimi, raporlama, "
                   "içerik planlama ve proje takibi.",
    "author": "ATLAS",
    "supported_languages": ["tr", "en"],
    "tags": ["digital_agency", "marketing", "advertising", "seo", "social_media"],
    "skills": [
        {
            "name": "ClientOnboarder",
            "description": "Yeni müşteri alım süreci",
            "category": "client_management",
            "required": True,
            "config": {
                "onboard_steps": ["brief", "contract", "access", "kickoff"],
                "checklist_template": True,
                "auto_create_project": True,
            },
            "dependencies": [],
        },
        {
            "name": "CampaignManager",
            "description": "Google/Meta/TikTok kampanya yönetimi",
            "category": "advertising",
            "required": True,
            "config": {
                "platforms": ["google_ads", "meta_ads", "tiktok_ads"],
                "auto_optimization": True,
                "budget_alert_threshold": 0.8,
                "performance_check_interval_hours": 4,
            },
            "dependencies": [],
        },
        {
            "name": "ReportGenerator",
            "description": "Otomatik performans raporu (haftalık/aylık)",
            "category": "reporting",
            "required": True,
            "config": {
                "report_types": ["weekly", "monthly", "campaign", "adhoc"],
                "formats": ["pdf", "excel", "google_slides"],
                "auto_send": True,
                "include_recommendations": True,
            },
            "dependencies": ["CampaignManager"],
        },
        {
            "name": "ContentCalendar",
            "description": "İçerik takvimi planlama ve hatırlatma",
            "category": "content",
            "required": True,
            "config": {
                "platforms": ["instagram", "facebook", "twitter", "linkedin", "tiktok"],
                "reminder_hours_before": 24,
                "approval_required": True,
            },
            "dependencies": [],
        },
        {
            "name": "BudgetTracker",
            "description": "Reklam bütçe takibi ve harcama uyarısı",
            "category": "financial",
            "required": True,
            "config": {
                "alert_at_percent": [50, 75, 90, 100],
                "daily_limit_enabled": True,
                "auto_pause_at_limit": True,
            },
            "dependencies": ["CampaignManager"],
        },
        {
            "name": "CompetitorAnalyzer",
            "description": "Rakip reklam ve SEO analizi",
            "category": "analysis",
            "required": False,
            "config": {
                "analysis_types": ["ads", "seo", "social", "content"],
                "check_interval_days": 7,
                "max_competitors": 5,
            },
            "dependencies": [],
        },
        {
            "name": "LeadScorer",
            "description": "Lead puanlama ve önceliklendirme",
            "category": "sales",
            "required": False,
            "config": {
                "scoring_criteria": ["budget", "timeline", "fit", "engagement"],
                "hot_lead_threshold": 80,
                "auto_assign": True,
            },
            "dependencies": [],
        },
        {
            "name": "InvoiceGenerator",
            "description": "Otomatik fatura oluşturma",
            "category": "financial",
            "required": True,
            "config": {
                "billing_cycle": "monthly",
                "auto_send": False,
                "include_performance_summary": True,
                "currency": "TRY",
            },
            "dependencies": [],
        },
        {
            "name": "ProjectTracker",
            "description": "Proje durumu takibi ve deadline uyarısı",
            "category": "project_management",
            "required": True,
            "config": {
                "deadline_alert_days_before": [7, 3, 1],
                "status_update_frequency": "daily",
                "blocker_escalation": True,
            },
            "dependencies": [],
        },
        {
            "name": "ClientCommunicator",
            "description": "Müşteri iletişim otomasyonu",
            "category": "communication",
            "required": True,
            "config": {
                "channels": ["email", "whatsapp", "slack"],
                "weekly_update_enabled": True,
                "auto_meeting_notes": True,
            },
            "dependencies": [],
        },
    ],
    "workflows": [
        {
            "name": "campaign_launch_flow",
            "description": "Brief → strateji → içerik → onay → yayın → optimizasyon",
            "trigger": "campaign_request",
            "steps": [
                {"name": "receive_brief", "step_type": "action", "skill_ref": "ClientOnboarder", "config": {"action": "receive_brief"}},
                {"name": "create_strategy", "step_type": "action", "skill_ref": "CampaignManager", "config": {"action": "create_strategy"}},
                {"name": "prepare_content", "step_type": "action", "skill_ref": "ContentCalendar", "config": {"action": "prepare"}},
                {"name": "client_approval", "step_type": "approval", "skill_ref": "ClientCommunicator", "config": {"approver": "client"}},
                {"name": "launch_campaign", "step_type": "action", "skill_ref": "CampaignManager", "config": {"action": "launch"}},
                {"name": "optimize", "step_type": "action", "skill_ref": "CampaignManager", "config": {"action": "optimize"}},
            ],
            "tags": ["campaign", "launch"],
        },
        {
            "name": "reporting_flow",
            "description": "Veri çek → analiz → rapor oluştur → müşteriye gönder",
            "trigger": "report_schedule",
            "steps": [
                {"name": "collect_data", "step_type": "action", "skill_ref": "CampaignManager", "config": {"action": "collect_metrics"}},
                {"name": "analyze", "step_type": "action", "skill_ref": "ReportGenerator", "config": {"action": "analyze"}},
                {"name": "generate_report", "step_type": "action", "skill_ref": "ReportGenerator", "config": {"action": "generate"}},
                {"name": "send_to_client", "step_type": "action", "skill_ref": "ClientCommunicator", "config": {"action": "send_report"}},
            ],
            "tags": ["reporting", "analytics"],
        },
        {
            "name": "client_management_flow",
            "description": "Onboard → proje başlat → haftalık güncelleme → fatura",
            "trigger": "new_client",
            "steps": [
                {"name": "onboard", "step_type": "action", "skill_ref": "ClientOnboarder", "config": {"action": "onboard"}},
                {"name": "create_project", "step_type": "action", "skill_ref": "ProjectTracker", "config": {"action": "create"}},
                {"name": "weekly_update", "step_type": "action", "skill_ref": "ClientCommunicator", "config": {"action": "weekly_update"}},
                {"name": "monthly_invoice", "step_type": "action", "skill_ref": "InvoiceGenerator", "config": {"action": "generate"}},
            ],
            "tags": ["client", "management"],
        },
    ],
    "crm_fields": [
        {"name": "company_name", "label": "Şirket Adı", "field_type": "text", "category": "company"},
        {"name": "industry", "label": "Sektör", "field_type": "select", "options": ["ecommerce", "saas", "healthcare", "education", "finance", "other"], "category": "company"},
        {"name": "monthly_budget", "label": "Aylık Bütçe", "field_type": "currency", "category": "financial"},
        {"name": "contract_value", "label": "Sözleşme Değeri", "field_type": "currency", "category": "financial"},
        {"name": "services", "label": "Hizmetler", "field_type": "multi_select", "options": ["google_ads", "meta_ads", "seo", "social_media", "content", "web_development"], "category": "services"},
        {"name": "account_manager", "label": "Hesap Yöneticisi", "field_type": "text", "category": "internal"},
        {"name": "contract_start", "label": "Sözleşme Başlangıcı", "field_type": "date", "category": "contract"},
        {"name": "contract_end", "label": "Sözleşme Bitişi", "field_type": "date", "category": "contract"},
        {"name": "satisfaction_score", "label": "Memnuniyet Puanı", "field_type": "rating", "category": "feedback"},
        {"name": "churn_risk", "label": "Kayıp Riski", "field_type": "select", "options": ["low", "medium", "high"], "category": "risk"},
    ],
    "crm_segments": [
        {"name": "enterprise", "description": "Büyük bütçeli kurumsal müşteriler", "criteria": {"monthly_budget_gt": 50000}},
        {"name": "growth", "description": "Büyüme odaklı orta ölçekli", "criteria": {"monthly_budget_between": [10000, 50000]}},
        {"name": "starter", "description": "Yeni başlayan küçük müşteriler", "criteria": {"monthly_budget_lt": 10000}},
        {"name": "at_risk", "description": "Kayıp riski yüksek müşteriler", "criteria": {"churn_risk": "high"}},
    ],
    "compliance_rules": [
        {"name": "ad_disclosure", "description": "Reklam ifşa kuralları", "level": "required", "category": "advertising", "jurisdictions": ["TR"]},
        {"name": "data_processing", "description": "Müşteri verisi işleme sözleşmesi", "level": "required", "category": "privacy", "jurisdictions": ["TR", "EU"]},
        {"name": "google_partner", "description": "Google Partner program kuralları", "level": "recommended", "category": "partnership", "jurisdictions": ["global"]},
        {"name": "meta_business", "description": "Meta Business Partner kuralları", "level": "recommended", "category": "partnership", "jurisdictions": ["global"]},
    ],
    "default_config": {
        "timezone": "Europe/Istanbul",
        "currency": "TRY",
        "language": "tr",
        "notification_channel": "slack",
        "working_hours": {"start": "09:00", "end": "18:00"},
        "report_day": "monday",
    },
}
