"""E-Commerce Agent şablon tanımı.

Sipariş takibi, müşteri destek, stok izleme,
fiyat optimizasyonu, yorum yönetimi, sepet kurtarma,
kargo koordinasyonu, kampanya yönetimi, iade işleme,
tedarikçi iletişim becerileri ve iş akışları.
"""

ECOMMERCE_TEMPLATE = {
    "name": "E-Commerce Agent",
    "industry": "ecommerce",
    "version": "1.0.0",
    "description": "E-ticaret operasyonları için tam kapsamlı AI agent şablonu. "
                   "Sipariş yönetimi, müşteri destek, stok takibi, fiyat optimizasyonu, "
                   "kampanya yönetimi ve tedarikçi koordinasyonu.",
    "author": "ATLAS",
    "supported_languages": ["tr", "en", "de", "ar"],
    "tags": ["ecommerce", "retail", "marketplace", "trendyol", "shopify"],
    "skills": [
        {
            "name": "OrderTracker",
            "description": "Sipariş durumu takip ve müşteriye bildirim",
            "category": "order_management",
            "required": True,
            "config": {
                "tracking_providers": ["yurtici", "aras", "mng", "ptt", "ups", "dhl"],
                "notification_channels": ["telegram", "email", "sms"],
                "auto_update_interval_minutes": 30,
            },
            "dependencies": [],
        },
        {
            "name": "CustomerSupportBot",
            "description": "Sık sorulan sorular, iade ve değişim desteği",
            "category": "customer_service",
            "required": True,
            "config": {
                "faq_categories": ["siparis", "kargo", "iade", "odeme", "urun"],
                "escalation_threshold": 3,
                "auto_response_enabled": True,
                "sentiment_tracking": True,
            },
            "dependencies": [],
        },
        {
            "name": "InventoryMonitor",
            "description": "Stok seviyesi izleme ve düşük stok uyarısı",
            "category": "inventory",
            "required": True,
            "config": {
                "low_stock_threshold": 10,
                "critical_stock_threshold": 3,
                "reorder_point_enabled": True,
                "sync_interval_minutes": 15,
            },
            "dependencies": [],
        },
        {
            "name": "PriceOptimizer",
            "description": "Rakip fiyat takibi ve dinamik fiyatlama önerisi",
            "category": "pricing",
            "required": False,
            "config": {
                "competitor_check_interval_hours": 6,
                "price_change_max_percent": 15,
                "margin_floor_percent": 10,
                "auto_adjust": False,
            },
            "dependencies": ["InventoryMonitor"],
        },
        {
            "name": "ReviewManager",
            "description": "Yorum toplama ve olumsuz yorum uyarısı",
            "category": "reputation",
            "required": False,
            "config": {
                "platforms": ["trendyol", "hepsiburada", "google", "trustpilot"],
                "negative_threshold": 3.0,
                "auto_response_positive": True,
                "alert_on_negative": True,
            },
            "dependencies": [],
        },
        {
            "name": "CartAbandonRecovery",
            "description": "Terk edilen sepet kurtarma mesajları",
            "category": "marketing",
            "required": False,
            "config": {
                "abandon_timeout_minutes": 60,
                "max_reminders": 3,
                "reminder_intervals_hours": [1, 24, 72],
                "discount_offer_enabled": True,
                "discount_percent": 10,
            },
            "dependencies": [],
        },
        {
            "name": "ShippingCoordinator",
            "description": "Kargo takip ve gecikme bildirimi",
            "category": "logistics",
            "required": True,
            "config": {
                "auto_select_cheapest": True,
                "delay_alert_hours": 24,
                "bulk_shipping_threshold": 10,
            },
            "dependencies": ["OrderTracker"],
        },
        {
            "name": "CampaignAssistant",
            "description": "Promosyon planlama ve performans raporlama",
            "category": "marketing",
            "required": False,
            "config": {
                "channels": ["email", "sms", "push", "telegram"],
                "ab_testing_enabled": True,
                "auto_report_interval": "weekly",
            },
            "dependencies": [],
        },
        {
            "name": "ReturnProcessor",
            "description": "İade talebi işleme ve onay akışı",
            "category": "order_management",
            "required": True,
            "config": {
                "auto_approve_under_tl": 200,
                "return_window_days": 14,
                "refund_method": "original_payment",
                "require_photo": True,
            },
            "dependencies": ["OrderTracker"],
        },
        {
            "name": "SupplierCommunicator",
            "description": "Tedarikçi sipariş ve takip otomasyonu",
            "category": "supply_chain",
            "required": False,
            "config": {
                "auto_reorder": False,
                "communication_channel": "email",
                "order_confirmation_required": True,
            },
            "dependencies": ["InventoryMonitor"],
        },
    ],
    "workflows": [
        {
            "name": "new_order_flow",
            "description": "Sipariş → onay → kargo → teslim → memnuniyet anketi",
            "trigger": "new_order",
            "steps": [
                {"name": "order_received", "step_type": "notification", "skill_ref": "OrderTracker", "config": {"message": "Yeni sipariş alındı"}},
                {"name": "payment_check", "step_type": "condition", "skill_ref": "OrderTracker", "config": {"check": "payment_confirmed"}},
                {"name": "prepare_shipment", "step_type": "action", "skill_ref": "ShippingCoordinator", "config": {"action": "create_shipment"}},
                {"name": "notify_customer", "step_type": "notification", "skill_ref": "OrderTracker", "config": {"message": "Kargoya verildi"}},
                {"name": "delivery_confirm", "step_type": "condition", "skill_ref": "ShippingCoordinator", "config": {"check": "delivered"}},
                {"name": "satisfaction_survey", "step_type": "action", "skill_ref": "ReviewManager", "config": {"action": "send_survey"}, "next_steps": []},
            ],
            "tags": ["order", "shipment", "customer"],
        },
        {
            "name": "return_flow",
            "description": "İade talebi → değerlendirme → onay → geri ödeme",
            "trigger": "return_request",
            "steps": [
                {"name": "receive_request", "step_type": "action", "skill_ref": "ReturnProcessor", "config": {"action": "receive"}},
                {"name": "evaluate", "step_type": "condition", "skill_ref": "ReturnProcessor", "config": {"check": "eligible"}},
                {"name": "approve_return", "step_type": "approval", "skill_ref": "ReturnProcessor", "config": {"approver": "auto_or_manager"}},
                {"name": "process_refund", "step_type": "action", "skill_ref": "ReturnProcessor", "config": {"action": "refund"}},
                {"name": "update_inventory", "step_type": "action", "skill_ref": "InventoryMonitor", "config": {"action": "restock"}},
            ],
            "tags": ["return", "refund"],
        },
        {
            "name": "restock_flow",
            "description": "Düşük stok → tedarikçi sipariş → takip → güncelleme",
            "trigger": "low_stock_alert",
            "steps": [
                {"name": "detect_low_stock", "step_type": "condition", "skill_ref": "InventoryMonitor", "config": {"check": "below_threshold"}},
                {"name": "create_po", "step_type": "action", "skill_ref": "SupplierCommunicator", "config": {"action": "create_purchase_order"}},
                {"name": "send_to_supplier", "step_type": "action", "skill_ref": "SupplierCommunicator", "config": {"action": "send_order"}},
                {"name": "track_delivery", "step_type": "action", "skill_ref": "SupplierCommunicator", "config": {"action": "track"}},
                {"name": "update_stock", "step_type": "action", "skill_ref": "InventoryMonitor", "config": {"action": "update_levels"}},
            ],
            "tags": ["inventory", "supplier", "restock"],
        },
        {
            "name": "campaign_flow",
            "description": "Kampanya oluştur → hedef kitle → gönder → raporla",
            "trigger": "campaign_create",
            "steps": [
                {"name": "create_campaign", "step_type": "action", "skill_ref": "CampaignAssistant", "config": {"action": "create"}},
                {"name": "select_audience", "step_type": "action", "skill_ref": "CampaignAssistant", "config": {"action": "target"}},
                {"name": "approve_campaign", "step_type": "approval", "skill_ref": "CampaignAssistant", "config": {"approver": "manager"}},
                {"name": "send_campaign", "step_type": "action", "skill_ref": "CampaignAssistant", "config": {"action": "send"}},
                {"name": "report_results", "step_type": "action", "skill_ref": "CampaignAssistant", "config": {"action": "report"}},
            ],
            "tags": ["marketing", "campaign"],
        },
    ],
    "crm_fields": [
        {"name": "customer_lifetime_value", "label": "Müşteri Yaşam Boyu Değeri", "field_type": "currency", "category": "financial"},
        {"name": "order_history", "label": "Sipariş Geçmişi", "field_type": "text", "category": "orders"},
        {"name": "preferred_channel", "label": "Tercih Edilen Kanal", "field_type": "select", "options": ["email", "sms", "whatsapp", "telegram"], "category": "communication"},
        {"name": "return_rate", "label": "İade Oranı", "field_type": "number", "category": "orders"},
        {"name": "satisfaction_score", "label": "Memnuniyet Puanı", "field_type": "rating", "category": "feedback"},
        {"name": "last_purchase_date", "label": "Son Satın Alma Tarihi", "field_type": "date", "category": "orders"},
        {"name": "total_orders", "label": "Toplam Sipariş", "field_type": "number", "category": "orders"},
        {"name": "avg_order_value", "label": "Ortalama Sipariş Değeri", "field_type": "currency", "category": "financial"},
        {"name": "favorite_categories", "label": "Favori Kategoriler", "field_type": "multi_select", "options": ["elektronik", "giyim", "kozmetik", "ev", "gida"], "category": "preferences"},
        {"name": "loyalty_points", "label": "Sadakat Puanı", "field_type": "number", "category": "loyalty"},
    ],
    "crm_segments": [
        {"name": "VIP", "description": "Yüksek değerli müşteriler (LTV > 5000 TL)", "criteria": {"customer_lifetime_value_gt": 5000}},
        {"name": "regular", "description": "Düzenli alışveriş yapan müşteriler", "criteria": {"total_orders_gt": 3}},
        {"name": "new", "description": "Son 30 günde ilk siparişini veren", "criteria": {"total_orders_eq": 1, "days_since_first_order_lt": 30}},
        {"name": "at_risk", "description": "Son 90 günde alışveriş yapmayan", "criteria": {"days_since_last_purchase_gt": 90}},
        {"name": "churned", "description": "Son 180 günde alışveriş yapmayan", "criteria": {"days_since_last_purchase_gt": 180}},
    ],
    "compliance_rules": [
        {"name": "kvkk_consent", "description": "KVKK aydınlatma metni ve onay", "level": "required", "category": "privacy", "jurisdictions": ["TR"]},
        {"name": "distance_selling", "description": "Mesafeli satış sözleşmesi", "level": "required", "category": "commerce", "jurisdictions": ["TR"]},
        {"name": "return_policy", "description": "14 gün cayma hakkı", "level": "required", "category": "consumer_rights", "jurisdictions": ["TR", "EU"]},
        {"name": "price_display", "description": "KDV dahil fiyat gösterimi", "level": "required", "category": "pricing", "jurisdictions": ["TR"]},
        {"name": "data_retention", "description": "Kişisel veri saklama süreleri", "level": "required", "category": "privacy", "jurisdictions": ["TR", "EU"]},
    ],
    "default_config": {
        "timezone": "Europe/Istanbul",
        "currency": "TRY",
        "language": "tr",
        "notification_channel": "telegram",
        "working_hours": {"start": "09:00", "end": "18:00"},
        "auto_approve_threshold_tl": 200,
    },
}
