"""Medical Tourism Agent şablon tanımı.

Çok dilli hasta kabul, tedavi teklifi, WhatsApp CRM,
klinik optimizasyonu, çeviri köprüsü, portfolio yönetimi,
uçuş/otel koordinasyonu, ameliyat sonrası takip,
yorum toplama, tıbbi reklam uyumluluğu.
"""

MEDICAL_TOURISM_TEMPLATE = {
    "name": "Medical Tourism Agent",
    "industry": "medical_tourism",
    "version": "1.0.0",
    "description": "Medikal turizm operasyonları için tam kapsamlı AI agent şablonu. "
                   "Hasta yönetimi, tedavi planlama, travel koordinasyonu, "
                   "çok dilli iletişim ve uyumluluk yönetimi.",
    "author": "ATLAS",
    "supported_languages": ["tr", "en", "de", "it", "fr", "bg", "ar", "ru"],
    "tags": ["medical", "tourism", "healthcare", "hair_transplant", "dental", "aesthetic"],
    "skills": [
        {
            "name": "PatientIntakeBot",
            "description": "Çok dilli hasta kabul (DE/IT/EN/FR/BG/TR)",
            "category": "patient_management",
            "required": True,
            "config": {
                "supported_languages": ["tr", "en", "de", "it", "fr", "bg", "ar", "ru"],
                "intake_channels": ["whatsapp", "telegram", "web_form", "email"],
                "auto_language_detect": True,
                "collect_medical_history": True,
            },
            "dependencies": [],
        },
        {
            "name": "TreatmentQuoteGen",
            "description": "Otomatik tedavi teklifi ve PDF oluşturma",
            "category": "sales",
            "required": True,
            "config": {
                "treatment_types": ["hair_transplant", "dental", "aesthetic", "eye", "bariatric"],
                "currency_options": ["EUR", "USD", "GBP", "TRY"],
                "include_travel_package": True,
                "pdf_branding": True,
            },
            "dependencies": ["PatientIntakeBot"],
        },
        {
            "name": "WhatsAppPatientCRM",
            "description": "Hasta takip ve randevu hatırlatma",
            "category": "patient_management",
            "required": True,
            "config": {
                "auto_reminder_hours_before": [48, 24, 2],
                "followup_schedule_days": [1, 7, 30, 90, 180],
                "message_templates_per_language": True,
            },
            "dependencies": [],
        },
        {
            "name": "ClinicSlotOptimizer",
            "description": "Klinik doluluk optimizasyonu",
            "category": "operations",
            "required": False,
            "config": {
                "max_daily_procedures": 10,
                "buffer_between_procedures_minutes": 30,
                "overbooking_percent": 10,
            },
            "dependencies": [],
        },
        {
            "name": "TranslationBridge",
            "description": "Gerçek zamanlı doktor-hasta çeviri",
            "category": "communication",
            "required": True,
            "config": {
                "medical_terminology": True,
                "real_time": True,
                "fallback_to_english": True,
            },
            "dependencies": [],
        },
        {
            "name": "BeforeAfterPortfolio",
            "description": "Öncesi/sonrası galeri yönetimi",
            "category": "marketing",
            "required": False,
            "config": {
                "consent_required": True,
                "auto_anonymize": True,
                "gallery_categories": ["hair", "dental", "rhinoplasty", "bbl"],
            },
            "dependencies": [],
        },
        {
            "name": "FlightHotelCoordinator",
            "description": "Uçuş ve otel paket koordinasyonu",
            "category": "travel",
            "required": True,
            "config": {
                "partner_hotels": [],
                "airport_transfer_included": True,
                "companion_accommodation": True,
            },
            "dependencies": ["PatientIntakeBot"],
        },
        {
            "name": "PostOpFollowUp",
            "description": "Ameliyat sonrası takip otomasyonu",
            "category": "patient_management",
            "required": True,
            "config": {
                "followup_days": [1, 3, 7, 14, 30, 90, 180, 365],
                "photo_request": True,
                "symptom_checklist": True,
                "emergency_escalation": True,
            },
            "dependencies": ["WhatsAppPatientCRM"],
        },
        {
            "name": "ReviewHarvester",
            "description": "Google/Trustpilot yorum toplama",
            "category": "reputation",
            "required": False,
            "config": {
                "platforms": ["google", "trustpilot", "realself", "whatclinic"],
                "request_after_days": 30,
                "incentive_enabled": False,
                "min_satisfaction_to_ask": 4,
            },
            "dependencies": ["PostOpFollowUp"],
        },
        {
            "name": "ComplianceGuard",
            "description": "Tıbbi reklam uyumluluk kontrolü",
            "category": "compliance",
            "required": True,
            "config": {
                "google_ads_policy": True,
                "meta_health_policy": True,
                "before_after_rules": True,
                "claim_verification": True,
            },
            "dependencies": [],
        },
    ],
    "workflows": [
        {
            "name": "patient_inquiry_flow",
            "description": "Sorgu → değerlendirme → teklif → onay → randevu",
            "trigger": "patient_inquiry",
            "steps": [
                {"name": "receive_inquiry", "step_type": "action", "skill_ref": "PatientIntakeBot", "config": {"action": "intake"}},
                {"name": "detect_language", "step_type": "action", "skill_ref": "TranslationBridge", "config": {"action": "detect"}},
                {"name": "collect_info", "step_type": "action", "skill_ref": "PatientIntakeBot", "config": {"action": "collect_details"}},
                {"name": "generate_quote", "step_type": "action", "skill_ref": "TreatmentQuoteGen", "config": {"action": "generate"}},
                {"name": "send_quote", "step_type": "notification", "skill_ref": "WhatsAppPatientCRM", "config": {"message": "treatment_quote"}},
                {"name": "followup_if_no_response", "step_type": "delay", "skill_ref": "WhatsAppPatientCRM", "config": {"delay_hours": 48}},
            ],
            "tags": ["inquiry", "sales", "patient"],
        },
        {
            "name": "treatment_flow",
            "description": "Varış → muayene → tedavi → kontrol → taburcu",
            "trigger": "patient_arrival",
            "steps": [
                {"name": "airport_pickup", "step_type": "action", "skill_ref": "FlightHotelCoordinator", "config": {"action": "pickup"}},
                {"name": "hotel_checkin", "step_type": "action", "skill_ref": "FlightHotelCoordinator", "config": {"action": "checkin"}},
                {"name": "clinic_examination", "step_type": "action", "skill_ref": "ClinicSlotOptimizer", "config": {"action": "schedule_exam"}},
                {"name": "treatment_day", "step_type": "action", "skill_ref": "ClinicSlotOptimizer", "config": {"action": "treatment"}},
                {"name": "post_op_check", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "day1_check"}},
                {"name": "discharge", "step_type": "notification", "skill_ref": "WhatsAppPatientCRM", "config": {"message": "discharge_instructions"}},
            ],
            "tags": ["treatment", "operations"],
        },
        {
            "name": "follow_up_flow",
            "description": "1 gün → 1 hafta → 1 ay → 3 ay → 6 ay kontrol",
            "trigger": "post_treatment",
            "steps": [
                {"name": "day1", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "check", "day": 1}},
                {"name": "week1", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "check", "day": 7}},
                {"name": "month1", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "check", "day": 30}},
                {"name": "month3", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "check", "day": 90}},
                {"name": "month6", "step_type": "action", "skill_ref": "PostOpFollowUp", "config": {"action": "check", "day": 180}},
            ],
            "tags": ["followup", "patient_care"],
        },
        {
            "name": "review_flow",
            "description": "Memnuniyet anketi → olumlu → yorum isteği",
            "trigger": "satisfaction_survey",
            "steps": [
                {"name": "send_survey", "step_type": "action", "skill_ref": "ReviewHarvester", "config": {"action": "send_survey"}},
                {"name": "check_score", "step_type": "condition", "skill_ref": "ReviewHarvester", "config": {"check": "score_gte_4"}},
                {"name": "request_review", "step_type": "action", "skill_ref": "ReviewHarvester", "config": {"action": "request_review"}},
                {"name": "add_to_portfolio", "step_type": "action", "skill_ref": "BeforeAfterPortfolio", "config": {"action": "request_photos"}},
            ],
            "tags": ["review", "reputation"],
        },
    ],
    "crm_fields": [
        {"name": "treatment_type", "label": "Tedavi Tipi", "field_type": "select", "options": ["hair_transplant", "dental", "rhinoplasty", "bbl", "eye_surgery", "bariatric"], "category": "medical"},
        {"name": "country", "label": "Ülke", "field_type": "text", "category": "demographics"},
        {"name": "language", "label": "Dil", "field_type": "select", "options": ["tr", "en", "de", "it", "fr", "bg", "ar", "ru"], "category": "communication"},
        {"name": "budget_range", "label": "Bütçe Aralığı", "field_type": "select", "options": ["economy", "standard", "premium", "vip"], "category": "financial"},
        {"name": "travel_dates", "label": "Seyahat Tarihleri", "field_type": "date", "category": "travel"},
        {"name": "hotel_preference", "label": "Otel Tercihi", "field_type": "select", "options": ["3_star", "4_star", "5_star", "apartment"], "category": "travel"},
        {"name": "companion_count", "label": "Refakatçi Sayısı", "field_type": "number", "category": "travel"},
        {"name": "medical_history", "label": "Tıbbi Geçmiş", "field_type": "text", "category": "medical"},
        {"name": "allergy_info", "label": "Alerji Bilgisi", "field_type": "text", "category": "medical"},
        {"name": "satisfaction_score", "label": "Memnuniyet Puanı", "field_type": "rating", "category": "feedback"},
        {"name": "referral_source", "label": "Referans Kaynağı", "field_type": "select", "options": ["google", "instagram", "referral", "agent", "other"], "category": "marketing"},
        {"name": "total_spend_eur", "label": "Toplam Harcama (EUR)", "field_type": "currency", "category": "financial"},
    ],
    "crm_segments": [
        {"name": "inquiry", "description": "İlk sorgu aşamasındaki hastalar", "criteria": {"status": "inquiry"}},
        {"name": "quoted", "description": "Teklif gönderilen hastalar", "criteria": {"status": "quoted"}},
        {"name": "booked", "description": "Randevu alan hastalar", "criteria": {"status": "booked"}},
        {"name": "treated", "description": "Tedavi olan hastalar", "criteria": {"status": "treated"}},
        {"name": "followup", "description": "Takip sürecindeki hastalar", "criteria": {"status": "followup"}},
        {"name": "completed", "description": "Süreci tamamlayan hastalar", "criteria": {"status": "completed"}},
    ],
    "compliance_rules": [
        {"name": "medical_advertising", "description": "Tıbbi reklam düzenlemeleri", "level": "required", "category": "advertising", "jurisdictions": ["TR"]},
        {"name": "patient_consent", "description": "Hasta aydınlatılmış onam", "level": "required", "category": "medical", "jurisdictions": ["TR", "EU"]},
        {"name": "data_protection", "description": "Sağlık verisi koruma (KVKK/GDPR)", "level": "required", "category": "privacy", "jurisdictions": ["TR", "EU"]},
        {"name": "before_after_photos", "description": "Öncesi/sonrası fotoğraf kuralları", "level": "required", "category": "advertising", "jurisdictions": ["TR"]},
        {"name": "cross_border_health", "description": "Sınır ötesi sağlık hizmeti düzenlemeleri", "level": "required", "category": "medical", "jurisdictions": ["EU"]},
        {"name": "google_health_ads", "description": "Google sağlık reklamları politikası", "level": "required", "category": "advertising", "jurisdictions": ["global"]},
    ],
    "default_config": {
        "timezone": "Europe/Istanbul",
        "currency": "EUR",
        "language": "en",
        "notification_channel": "whatsapp",
        "working_hours": {"start": "08:00", "end": "20:00"},
        "emergency_contact": True,
    },
}
