"""Real Estate Agent şablon tanımı.

Lead yakalama, mülk eşleştirme, gösterim planlama,
fiyat analizi, belge oluşturma, takip yönetimi,
ilan yayını, kredi hesaplama, bölge bilgisi,
portföy raporlama becerileri ve iş akışları.
"""

REAL_ESTATE_TEMPLATE = {
    "name": "Real Estate Agent",
    "industry": "real_estate",
    "version": "1.0.0",
    "description": "Gayrimenkul operasyonları için tam kapsamlı AI agent şablonu. "
                   "Lead yönetimi, mülk eşleştirme, gösterim planlama, "
                   "fiyat analizi ve sözleşme yönetimi.",
    "author": "ATLAS",
    "supported_languages": ["tr", "en"],
    "tags": ["real_estate", "property", "emlak", "gayrimenkul"],
    "skills": [
        {
            "name": "LeadCaptureBot",
            "description": "Çoklu kanaldan lead yakalama",
            "category": "sales",
            "required": True,
            "config": {
                "channels": ["website", "sahibinden", "hepsiemlak", "whatsapp", "telegram", "phone"],
                "auto_respond": True,
                "lead_scoring": True,
                "qualification_questions": ["budget", "location", "property_type", "timeline"],
            },
            "dependencies": [],
        },
        {
            "name": "PropertyMatcher",
            "description": "Müşteri tercihi ve mülk eşleştirme",
            "category": "matching",
            "required": True,
            "config": {
                "match_criteria": ["location", "price", "size", "rooms", "features"],
                "similarity_threshold": 0.7,
                "max_suggestions": 5,
            },
            "dependencies": ["LeadCaptureBot"],
        },
        {
            "name": "ViewingScheduler",
            "description": "Gösterim randevusu planlama",
            "category": "operations",
            "required": True,
            "config": {
                "max_daily_viewings": 8,
                "buffer_minutes": 30,
                "reminder_hours_before": [24, 2],
                "calendar_sync": True,
            },
            "dependencies": ["PropertyMatcher"],
        },
        {
            "name": "PriceAnalyzer",
            "description": "Bölgesel fiyat analizi ve değerleme",
            "category": "analysis",
            "required": True,
            "config": {
                "data_sources": ["sahibinden", "hepsiemlak", "tapudata"],
                "comparable_radius_km": 2,
                "max_comparables": 10,
            },
            "dependencies": [],
        },
        {
            "name": "DocumentGenerator",
            "description": "Sözleşme ve teklif belgesi oluşturma",
            "category": "legal",
            "required": True,
            "config": {
                "templates": ["sales_agreement", "rental_agreement", "offer_letter", "power_of_attorney"],
                "auto_fill": True,
                "pdf_output": True,
            },
            "dependencies": [],
        },
        {
            "name": "FollowUpManager",
            "description": "Otomatik takip mesajları",
            "category": "sales",
            "required": True,
            "config": {
                "followup_intervals_days": [1, 3, 7, 14, 30],
                "channels": ["whatsapp", "phone", "email"],
                "max_followups": 5,
            },
            "dependencies": ["LeadCaptureBot"],
        },
        {
            "name": "ListingPublisher",
            "description": "Çoklu platform ilan yayını",
            "category": "marketing",
            "required": False,
            "config": {
                "platforms": ["sahibinden", "hepsiemlak", "emlakjet"],
                "auto_renew": True,
                "photo_optimization": True,
            },
            "dependencies": [],
        },
        {
            "name": "MortgageCalculator",
            "description": "Kredi hesaplayıcı ve banka yönlendirme",
            "category": "financial",
            "required": False,
            "config": {
                "banks": ["ziraat", "vakifbank", "halkbank", "isbank", "garanti"],
                "max_term_months": 120,
                "include_insurance": True,
            },
            "dependencies": [],
        },
        {
            "name": "NeighborhoodInfo",
            "description": "Bölge bilgisi (okul, ulaşım, alışveriş)",
            "category": "information",
            "required": False,
            "config": {
                "info_categories": ["schools", "transport", "shopping", "hospitals", "parks"],
                "radius_km": 3,
            },
            "dependencies": [],
        },
        {
            "name": "PortfolioReporter",
            "description": "Portföy performans raporu",
            "category": "reporting",
            "required": False,
            "config": {
                "report_frequency": "weekly",
                "include_market_trends": True,
                "include_lead_funnel": True,
            },
            "dependencies": [],
        },
    ],
    "workflows": [
        {
            "name": "lead_to_sale_flow",
            "description": "Lead → ihtiyaç analizi → eşleştirme → gösterim → teklif → satış",
            "trigger": "new_lead",
            "steps": [
                {"name": "capture_lead", "step_type": "action", "skill_ref": "LeadCaptureBot", "config": {"action": "capture"}},
                {"name": "qualify_lead", "step_type": "action", "skill_ref": "LeadCaptureBot", "config": {"action": "qualify"}},
                {"name": "match_properties", "step_type": "action", "skill_ref": "PropertyMatcher", "config": {"action": "match"}},
                {"name": "schedule_viewing", "step_type": "action", "skill_ref": "ViewingScheduler", "config": {"action": "schedule"}},
                {"name": "post_viewing_followup", "step_type": "action", "skill_ref": "FollowUpManager", "config": {"action": "post_viewing"}},
                {"name": "generate_offer", "step_type": "action", "skill_ref": "DocumentGenerator", "config": {"action": "offer_letter"}},
            ],
            "tags": ["lead", "sales", "viewing"],
        },
        {
            "name": "listing_flow",
            "description": "Mülk girişi → fotoğraf → ilan → yayın → lead takip",
            "trigger": "new_listing",
            "steps": [
                {"name": "create_listing", "step_type": "action", "skill_ref": "ListingPublisher", "config": {"action": "create"}},
                {"name": "price_analysis", "step_type": "action", "skill_ref": "PriceAnalyzer", "config": {"action": "analyze"}},
                {"name": "publish_listing", "step_type": "action", "skill_ref": "ListingPublisher", "config": {"action": "publish"}},
                {"name": "monitor_inquiries", "step_type": "action", "skill_ref": "LeadCaptureBot", "config": {"action": "monitor"}},
            ],
            "tags": ["listing", "marketing"],
        },
        {
            "name": "closing_flow",
            "description": "Teklif kabul → ekspertiz → sözleşme → tapu → teslim",
            "trigger": "offer_accepted",
            "steps": [
                {"name": "arrange_appraisal", "step_type": "action", "skill_ref": "PriceAnalyzer", "config": {"action": "appraisal"}},
                {"name": "prepare_contract", "step_type": "action", "skill_ref": "DocumentGenerator", "config": {"action": "sales_agreement"}},
                {"name": "mortgage_process", "step_type": "action", "skill_ref": "MortgageCalculator", "config": {"action": "process"}},
                {"name": "title_transfer", "step_type": "notification", "skill_ref": "DocumentGenerator", "config": {"message": "title_ready"}},
                {"name": "handover", "step_type": "action", "skill_ref": "FollowUpManager", "config": {"action": "handover_complete"}},
            ],
            "tags": ["closing", "legal"],
        },
    ],
    "crm_fields": [
        {"name": "property_interest", "label": "Mülk İlgi Alanı", "field_type": "select", "options": ["buy", "rent", "invest"], "category": "preference"},
        {"name": "budget_min", "label": "Min Bütçe", "field_type": "currency", "category": "financial"},
        {"name": "budget_max", "label": "Max Bütçe", "field_type": "currency", "category": "financial"},
        {"name": "preferred_location", "label": "Tercih Edilen Konum", "field_type": "text", "category": "preference"},
        {"name": "property_type", "label": "Mülk Tipi", "field_type": "select", "options": ["apartment", "villa", "office", "land", "shop"], "category": "preference"},
        {"name": "min_rooms", "label": "Min Oda Sayısı", "field_type": "number", "category": "preference"},
        {"name": "viewing_count", "label": "Gösterim Sayısı", "field_type": "number", "category": "activity"},
        {"name": "lead_score", "label": "Lead Puanı", "field_type": "number", "category": "sales"},
        {"name": "lead_source", "label": "Lead Kaynağı", "field_type": "select", "options": ["sahibinden", "hepsiemlak", "referral", "website", "phone"], "category": "marketing"},
        {"name": "timeline", "label": "Zaman Çizelgesi", "field_type": "select", "options": ["immediate", "1_month", "3_months", "6_months", "exploring"], "category": "preference"},
    ],
    "crm_segments": [
        {"name": "hot_leads", "description": "Acil alıcılar (yüksek puan, kısa zaman)", "criteria": {"lead_score_gt": 80, "timeline": "immediate"}},
        {"name": "investors", "description": "Yatırım amaçlı arayanlar", "criteria": {"property_interest": "invest"}},
        {"name": "first_time_buyers", "description": "İlk kez ev alacaklar", "criteria": {"viewing_count_lt": 3}},
        {"name": "renters", "description": "Kiralık arayanlar", "criteria": {"property_interest": "rent"}},
    ],
    "compliance_rules": [
        {"name": "tapu_registration", "description": "Tapu ve kadastro kayıt zorunluluğu", "level": "required", "category": "legal", "jurisdictions": ["TR"]},
        {"name": "anti_money_laundering", "description": "Kara para aklama önleme", "level": "required", "category": "financial", "jurisdictions": ["TR", "EU"]},
        {"name": "broker_license", "description": "Emlak komisyonculuk yetki belgesi", "level": "required", "category": "professional", "jurisdictions": ["TR"]},
        {"name": "fair_housing", "description": "Ayrımcılık yapmama politikası", "level": "required", "category": "ethics", "jurisdictions": ["TR", "EU"]},
    ],
    "default_config": {
        "timezone": "Europe/Istanbul",
        "currency": "TRY",
        "language": "tr",
        "notification_channel": "whatsapp",
        "working_hours": {"start": "09:00", "end": "19:00"},
        "commission_percent": 2,
    },
}
